# --- INCEPTION: MAIN NGINX CONFIGURATION ---
events {
    worker_connections 1024;
}
http {
    # Include standard media types (so CSS and images load properly)
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server {
        # 1. SECURITY: Listen ONLY on port 443 (HTTPS)
        listen 443 ssl;
        listen [::]:443 ssl;
        # 2. SECURITY: Enforce modern TLS protocols (42 Subject Requirement)
        ssl_protocols TLSv1.2 TLSv1.3;
        # Point to the SSL certificates we generated in the Dockerfile
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;
        # 3. ROUTING: Set your specific 42 domain name
        server_name danoguer.42.fr;
        # The shared folder where WordPress lives
        root /var/www/html;
        # The default files to look for when someone visits your domain
        index index.php index.html index.htm;
        # 4. STANDARD REQUESTS: Try to find the file, otherwise return a 404 error
        location / {
            try_files $uri $uri/ =404;
        }
        # 5. THE MAGIC FASTCGI PROXY: How NGINX talks to WordPress
        # If the requested file ends in .php, trigger this block
        location ~ \.php$ {
            # Split the URL to handle the PHP script execution
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            # Send the request over the internal network to the WordPress container on port 9000
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            # Tell PHP-FPM exactly where to find the file on its own hard drive
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
        location /adminer {
            # This sends the request to the adminer container
            proxy_pass http://adminer:8080;
            # Standard proxy headers to ensure Adminer knows the real URL
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /portfolio {
            # We use alias so NGINX knows where the root of the static site is
            proxy_pass http://static:80/;
            proxy_set_header Host $host;
        }
        location /cadvisor/ {
            proxy_pass http://cadvisor:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect / /cadvisor/;
        }
    }
}